server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hana0627/E-commerce
#          uri: file:///C:/hana/study/E-commerce/ecommerce.yml